name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Setup signing KeyStore
      if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
      run: |
        base64 --decode <<< "$JAVA_KEYSTORE_DATA" > "$JAVA_KEYSTORE_FILE"
        JAVA_KEYSTORE_FILE="${JAVA_KEYSTORE_FILE//\\/\\\\}" \
        envsubst < "$GITHUB_WORKSPACE/.github/workflows/keystore.properties" > "$KEYSTORE_PROPERTIES_FILE"
        echo "KEYSTORE_PROPERTIES_FILE=$KEYSTORE_PROPERTIES_FILE" >> "$GITHUB_ENV"
      shell: bash
      env:
        JAVA_KEYSTORE_ALIAS: ${{ secrets.JAVA_KEYSTORE_ALIAS }}
        JAVA_KEYSTORE_DATA: ${{ secrets.JAVA_KEYSTORE_DATA }}
        JAVA_KEYSTORE_FILE: ${{ runner.temp }}/keystore.jks
        JAVA_KEYSTORE_PASSWORD: ${{ secrets.JAVA_KEYSTORE_PASSWORD }}
        KEYSTORE_PROPERTIES_FILE: ${{ runner.temp }}/keystore.properties
    - run: ./gradlew build signingReport
    - name: Prep consolidated build outputs
      run: |
        mkdir -p "$RUNNER_TEMP/build-outputs"
        mv 'app/build/outputs' "$RUNNER_TEMP/build-outputs"
      shell: bash
    - name: Upload build outputs
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: ${{ runner.temp }}
        if-no-files-found: error
